# Generated by Django 4.2.24 on 2025-09-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todomodel_duedate_todomodel_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('primary', '低'), ('warning', '中'), ('danger', '高')], default='warning', max_length=10),
        ),
    ]
